services:
  mongo:
    image: mongo
    container_name: mongo-db
    ports:
      - "27017:27017"
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: mongoAdmin
      MONGO_INITDB_ROOT_PASSWORD: mongoAdmin123
      MONGO_INITDB_DATABASE: task-pro-db
    volumes:
      - ./db_data/:/data/db/

  task-pro-service:
    build: ./git
    container_name: task-pro-service
    ports:
      - "3000:3000"
    restart: always
    environment:
      DB_HOST: mongodb://mongoAdmin:mongoAdmin123@mongo:27017/admin
      PORT: 3000
      EXPIRES_TIME: 23h
      SEND_GRID_API_KEY: ""
      SEND_GRID_FROM: ""
      BASE_URL: http://task-pro-service:3000
      GOOGLE_CLIENT_ID: your_Id
      GOOGLE_CLIENT_SECRET: your_secret
      FRONTEND_URL: ""
      SEND_MAIL_USER: your_postal_service_email
      SEND_MAIL_PASS: your_postal_service_password
      SEND_MAIL_HOST: your_postal_service_host
      SEND_MAIL_PORT: your_postal_service_port
      SEND_HELP_MAIL: mail_to_which_notifications_should_be_sent
      CLOUDINARY_NAME: your_acc
      CLOUDINARY_KEY: your_key
      CLOUDINARY_SECRET: your_secret_key

      #token configuration
      ACCESS_SECRET_KEY: any_key
      REFRESH_SECRET_KEY: any_key
      ACCESS_EXPIRES_TIME: 2m
      REFRESH_EXPIRES_TIME: 7d
      SECRET_KEY: any_key
